service: plysheet

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  environment:
    DB: ${file(./variables.json):DB}
  
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: www.blockometry.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  get:
    handler: ply.port
    events:
      - http:
          method: get
          path: /{site}/{method}
          cors: true
  post:
    handler: ply.port
    events:
      - http:
          method: post
          path: /{site}/{method}
          cors: true
  put:
    handler: ply.port
    events:
      - http:
          method: put
          path: /{site}/{method}
          cors: true
  delete:
    handler: ply.port
    events:
      - http:
          method: delete
          path: /{site}/{method}
          cors: true

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
